/*
 * @Author: fujiawei0724
 * @Date: 2021-12-12 16:51:30
 * @LastEditors: fujiawei0724
 * @LastEditTime: 2021-12-14 15:23:45
 * @Description: Realization of the HPDM behavior planner based on reinforcement learning.
 */

#pragma once


#include "Const.hpp"
#include "VehicleState.hpp"
#include "BehaviorPlanner.hpp"

namespace HpdmPlanner {

using namespace Common;

class ActionInterface {
 public:
    /**
     * TODO: only support predicted time 4.0s with a time gap 0.4s, add more support parameters here
     * @brief transform an action index to a behavior sequence
     * @param action_index action index generate by model
     * @return behavior sequence
     */    
    static std::vector<VehicleBehavior> indexToBehSeq(const int& action_index);

    /**
     * TODO: only support predicted time 4.0s with a time gap 0.4s, add more support parameters here
     * @brief transform an action index to a intention sequence
     * @param action_index action index generate by model
     * @return intention sequence
     */    
    static std::vector<VehicleIntention> indexToIntentionSeq(const int& action_index);

};



/**
 * @brief transform vehicles state and lanes information to state 
 * @param nearest_lane nearest_lane for ego_vehicle
 * @return {*}
 */
class StateInterface {
 public:
    StateInterface(const Lane& nearest_lane);
    StateInterface();
    ~StateInterface();

    /**
     * @brief generate state from environment information
     * @param lane_info lane information
     * @param ego_vehicle ego vehicle information
     * @param sur_vehicles surround vehicles information
     * @param state state array generated
     */
    void runOnce(const std::vector<double>& lane_info, const Vehicle& ego_vehicle, const std::unordered_map<int, Vehicle>& sur_vehicles, std::vector<double>* state);

    /**
     * @brief transform single vehicle state
     * @param {*}
     * @return {*}
     */    
    std::vector<double> transformEgoVehicleState(const Vehicle& vehicle);

    /**
     * TODO: maybe a logic could be added here to distinct the differerce of different surround vehicles
     * @brief transform surround vehicles states
     * @param {*}
     * @return {*}
     */    
    std::vector<double> transformSurroundVehicleState(const std::unordered_map<int, Vehicle>& sur_vehicles);

    StateTransformer* stf_{nullptr};
    
};

// Interface with libtorch
class TorchInterface {
 public:
    TorchInterface(const std::string& model_path);
    ~TorchInterface();

    /**
     * @brief generate best action index from forwarding model
     * @param state state inputed to the model
     * @param action_index action generated by model
     */    
    void runOnce(const std::vector<double>& state, int* action_index);

    std::string model_path_;
};

class TrajectoryGenerator {
 public:
    using Trajectory = std::vector<Vehicle>;
    using BehaviorSequence = std::vector<VehicleBehavior>;
    using IntentionSequence = std::vector<VehicleIntention>;
    TrajectoryGenerator(BehaviorPlanner::MapInterface* map_itf, double dt = 0.4);
    ~TrajectoryGenerator();

    /**
     * @brief Simulate single behavior sequence
     * @param surround_vehicles
     * @param ego_vehicle
     * @param behavior_sequence
     * @param ego_traj
     * @param safe
     * @param cost
     */    
    void simulateSingleBehaviorSequence(const Vehicle& ego_vehicle, const std::unordered_map<int, Vehicle>& surround_vehicles, const BehaviorSequence& behavior_sequence, Trajectory* ego_traj, std::unordered_map<int, Trajectory>* sur_trajs, bool* safe, double* cost, Lane* target_behavior_reference_lane);

    /**
     * @brief Simulate single behavior sequence
     * @param surround_vehicles
     * @param ego_vehicle
     * @param behavior_sequence
     * @param ego_traj
     * @param safe
     * @param cost
     */    
    void simulateSingleIntentionSequence(const Vehicle& ego_vehicle, const std::unordered_map<int, Vehicle>& surround_vehicles, const IntentionSequence& intention_sequence, Trajectory* ego_traj, std::unordered_map<int, Trajectory>* sur_trajs, bool* safe, double* cost, Lane* target_intention_reference_lane);

    // Simulate single vehicle behavior (lateral and longitudinal)
    void simulateSingleBehavior(const SemanticVehicle& ego_semantic_vehicle, const std::unordered_map<int, SemanticVehicle>& surround_semantic_vehicles, const double& ego_desired_velocity, Vehicle& ego_vehicle_next_state, std::unordered_map<int, Vehicle>& surround_vehicles_next_states);

    BehaviorPlanner::MapInterface* map_itf_{nullptr};
    double dt_{0.0};
};

class HpdmPlannerCore {
 public:
    HpdmPlannerCore(BehaviorPlanner::MapInterface* map_itf, const Lane& nearest_lane, const std::string& model_path);
    HpdmPlannerCore(BehaviorPlanner::MapInterface* map_itf, const Lane& nearest_lane, const std::string& model_path, const ros::Publisher& vis_pub);
    ~HpdmPlannerCore();

    // Load data
    void load(const Vehicle& ego_vehicle, const std::unordered_map<int, Vehicle>& surround_vehicles, const std::vector<double>& lane_info);

    // Run HPDM planner
    void runHpdmPlanner(int lon_candidate_num, std::vector<Vehicle>* ego_traj, std::unordered_map<int, std::vector<Vehicle>>* sur_trajs, Lane* target_reference_lane, bool* safe, double* cost);

    TrajectoryGenerator* traj_generator_{nullptr};
    StateInterface* state_itf_{nullptr};
    TorchInterface* torch_itf_{nullptr};
    // DEBUG visualization
    ros::Publisher vis_pub_;

    Vehicle ego_vehicle_;
    std::unordered_map<int, Vehicle> surround_vehicles_;
    std::vector<double> lane_info_;

};

} // End of namespace HpdmPlanner
